## Practice of numpy

In [1]:
import numpy as np 

## Array Creation

In [4]:
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)

array_2d = np.full((3,4),7)
print("2D Array Of 7:\n",array_2d)

identity_matrix = np.ones((5,5))
print("Identity Matrix:",identity_matrix)

1D Array: [1 2 3 4 5]
2D Array Of 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Identity Matrix: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Array Slicing

In [20]:
array = np.array([10,20,30,40,50])
print("Last Three Elements Of Array:",array[2:])
print("Reversed Array:",array[-1:-6:-1])
print("2nd Way To Reverse:",array[::-1])

Last Three Elements Of Array: [30 40 50]
Reversed Array: [50 40 30 20 10]
2nd Way To Reverse: [50 40 30 20 10]


## Array Operation 

In [ ]:
arr1 = np.array([10,12,14,16,18])
arr2 = np.array([2,4,6,8,10])
print("Array Addition:",arr1+arr2)
print("Array SUbstraction:",arr1-arr2)
print("Array Multiplication:",arr1*arr2)
print("Array Division:",arr1/arr2)
print("Array1 Square:",np.square(arr1))
print("Array2 Square:",np.square(arr2))

Array Addition: [12 16 20 24 28]
Array SUbstraction: [8 8 8 8 8]
Array Multiplication: [ 20  48  84 128 180]
Array Division: [5.         3.         2.33333333 2.         1.8       ]
Array1 Square: [100 144 196 256 324]
Array2 Square: [  4  16  36  64 100]


## Masking

In [36]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
mask = numbers > 6
print("Numbers Greater than 6:",numbers[mask])

Numbers Greater than 6: [ 7  8  9 10]


## Reshape and Flatten 

In [45]:
arr = np.arange(0,12)
reshape_arr = arr.reshape(3,4)
print("Reshaped to 2D Array:",reshape_arr)
flatened_arr = reshape_arr.flatten()
print("Faltened 2D Array to Again 1D Array:",flatened_arr)

Reshaped to 2D Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Faltened 2D Array to Again 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Matrix Multiplication or Dot Product

In [ ]:
matrix_1 = np.random.randint(0,16,(2,3))
matrix_2 = np.random.randint(0,16,(3,2))
print("Matrix 1:",matrix_1)
print("Matrix 2:",matrix_2)
print("Marix Multiplication:",np.dot(matrix_1,matrix_2))



Matrix 1: [[ 0  5  4]
 [14  6  9]]
Matrix 2: [[14  3]
 [ 5  1]
 [ 8  6]]
Marix Multiplication: [[ 57  29]
 [298 102]]


## 4x4 Matrix and its mean medean 

In [54]:
rand_arr = np.random.randint(10,40,(4,4))
print("Random Matrix:",rand_arr)
print("Mean:",np.mean(rand_arr))
print("Median:",np.median(rand_arr))

Random Matrix: [[21 31 28 24]
 [36 37 27 24]
 [34 29 22 22]
 [39 36 39 23]]
Mean: 29.5
Median: 28.5


## Set Operations

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("Element Common In Both:",np.intersect1d(a, b))

print("Element in a but not in b:",np.setdiff1d(a,b))

Element Common In Both: [3 4]
Element in a but not in b: [1 2]
