## Numpy Array Creation 

In [1]:
import numpy as np

## Slicing with 1D Array 

In [2]:
arr = np.arange(11)
print("Array:",arr)
print("Basic Slicing:",arr[2:8])    #8 Exclusive
print("Basic Slicing with step:",arr[2:8:2])
print("Slicing with Negative Indexing:",arr[-5])

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing: [2 3 4 5 6 7]
Basic Slicing with step: [2 4 6]
Slicing with Negative Indexing: 6


## Slicing with 2D Array 

In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Random Array of Integer:\n", arr_2d)
print("Accessing Specific Element:",arr_2d[2,1])    #2nd Row and its 1st element
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,2])   #All Rows with but their 2nd Column 


Random Array of Integer:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Accessing Specific Element: 8
Entire Row: [4 5 6]
Entire Column: [3 6 9]


## Sorting 

In [4]:
# axis=0 = vertical axis = top to bottom = down the rows = affects columns
# axis=1 = horizontal axis = left to right = across the columns = affects rows
unsorted_arr = np.array([3,4,1,5,8,2,9])
print("Sorted Array,",np.sort(unsorted_arr))

arr_2d_unsortArr = np.array([[3,1],
                             [1,2],
                             [2,3]])
print("Sorted 2D Array By Column:\n",np.sort(arr_2d_unsortArr,axis=0))
print("Sorted 2D Array By Row:\n",np.sort(arr_2d_unsortArr,axis=1))

Sorted Array, [1 2 3 4 5 8 9]
Sorted 2D Array By Column:
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array By Row:
 [[1 3]
 [1 2]
 [2 3]]


## Filter 

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
evenNumbers = numbers[numbers % 2 == 0]
print("Even Numbers:",evenNumbers)

oddNumbers = numbers[numbers % 2 != 0]
print("Odd Numbers:",oddNumbers) 

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


## Filter With Mask 

In [6]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
mask1 = num > 5
mask2 = num % 2 == 0
mask3 = num % 2 != 0
print("Numbers Greater than 5:",num[mask1])
print("Even Numbers:",num[mask2])
print("Odd Numbers:",num[mask3])

Numbers Greater than 5: [ 6  7  8  9 10]
Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


## Fancy Indexing vs np.where

In [7]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,5,9]
print("Number with above indices:",num[indices])

whereResult = np.where(num < 5)
print("Num using NP Where:",num[whereResult])

Number with above indices: [ 1  6 10]
Num using NP Where: [1 2 3 4]


## Conditioned Array 

In [8]:
arr = np.array([1,2,3,4,5])
conditioned_arr = np.where(arr>3, arr*2, arr)   # Where element >3 return that elements where !>3 return multiply by 2
con_arr_BetterUnderstanding = np.where(arr>3, "True", "False")  # Where element >3 return true where !>3 return false
print("Conditioned Array:",conditioned_arr)
print("Conditioned Array for Better Understanding:",con_arr_BetterUnderstanding)


Conditioned Array: [ 1  2  3  8 10]
Conditioned Array for Better Understanding: ['False' 'False' 'False' 'True' 'True']


## Merging Two Array

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
wrong_merge_arr = arr1 + arr2    #This will give sum of elemnt by element
print("Wrong Merged Array:",wrong_merge_arr)

right_merge_arr = np.concat((arr1,arr2))
print("Right Merged Array:",right_merge_arr)

Wrong Merged Array: [5 7 9]
Right Merged Array: [1 2 3 4 5 6]


## Array Compatibility

In [10]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
print("Shape Compatbility:",a1.shape==a2.shape==a3.shape)

Shape Compatbility: True


## Adding New Things Like Rows and Columns etc in Exisitng Array

In [11]:
org_arr = np.array([[1,2],
                    [3,4]])
new_row = np.array([[5,6]])

arr_with_new_row = np.vstack((org_arr,new_row)) #vstack always add row
print("Original Array:\n ",org_arr)
print("Array With Addition Of Row:\n ",arr_with_new_row)

new_column = np.array([[7],[8]])
arr_with_new_col = np.hstack((org_arr,new_column)) #hstack always add row
print("Original Array:\n ",org_arr)
print("Array With Addition Of Column:",arr_with_new_col)

Original Array:
  [[1 2]
 [3 4]]
Array With Addition Of Row:
  [[1 2]
 [3 4]
 [5 6]]
Original Array:
  [[1 2]
 [3 4]]
Array With Addition Of Column: [[1 2 7]
 [3 4 8]]


## Deletion in Array 

In [12]:
arr = np.array([1,2,3,4,5,6,7])
deleted_arr = np.delete(arr,2)    #This Delete will return deleted Array not that deleted element
print("Array After Deletion of Element At Index 2:",deleted_arr)

Array After Deletion of Element At Index 2: [1 2 4 5 6 7]
