## Numpy array and basics
learn about numpy

In [11]:
import numpy as np


In [12]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]


### Numpy Array vs List

In [13]:

import time

py_list = [1,2,3]       #List multiplication repeats the list
print("List Multiplication", py_list*2)

np_array = np.array([1,2,3])      #NumPy array multiplication multiplies each element.
print("Array Multiplication", np_array*2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time:",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy Operation time:",time.time()-start)


List Multiplication [1, 2, 3, 1, 2, 3]
Array Multiplication [2 4 6]

 List Operation time: 0.13977646827697754

 Numpy Operation time: 0.011434316635131836


## Creating Array from Scratch 

In [19]:
zeros = np.zeros((3,4))
print("Zero Array: \n", zeros)

ones = np.ones((3,4))
print("One Array: \n", ones)

full = np.full((3,4),27)
print("Full Array: \n", full)

#We used this most 
random = np.random.random((3,4))
print("Random Array: \n", random)

#Random Array with Integer from 1 to 100
random = np.random.randint(0, 100, (3, 4))
print("Random Array of Integer:\n", random)

#Sequence Array 
sequence = np.arange(0,10,2)
print("Sequence Array:\n",sequence)



Zero Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[27 27 27 27]
 [27 27 27 27]
 [27 27 27 27]]
Random Array: 
 [[0.51941357 0.25617676 0.46143919 0.99683209]
 [0.63301139 0.28341368 0.91550932 0.45610571]
 [0.69125712 0.03923056 0.86332515 0.86122455]]
Random Array of Integer:
 [[87 43 62 22]
 [79 57 16 28]
 [81  5 79 44]]
Sequence Array:
 [0 2 4 6 8]


## Vector, Matrix and Tenser

In [20]:
#Vector(1D Array)
vector = np .array([1,2,3])
print("Vector:",vector)

#Matrix(2D Array)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:\n",matrix)

#Tensor(Multidimensional Array)
tensor = np.array([
  [[1,2],[3,4]],
  [[5,6],[7,8]]
  ])
print("Tensor:\n",tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [21]:
array = np.array([[1,2,3],
[4,5,6]
])
print("Shape:",array.shape)
print("Dimension:",array.ndim)
print("Size:",array.size)
print("Data Type:",array.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


## Array Reshaping

In [22]:
array = np.arange(12)
print("Array:",array)

reshaped = array.reshape((3,4))
print("Reshaped Array: \n",reshaped)

#Return copy of Array 
flatened = array.flatten()        #Convert to 1D
print("Flatened Array:",flatened)

#Return orignal Array instead of copy 
raveled = array.ravel()       
print("Raveled Array:",raveled)

#Transpose
transpose = reshaped.transpose()
print("Transponse:\n",transpose)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transponse:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
