## Simple Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
X = [[1],[2],[3],[4],[5]]   #Studied hours
y = [0,0,0,1,1] #0 = Fail, 1 = Pass

model = LogisticRegression()
model.fit(X,y)

hours = float(input("Enter Hours Studied: "))
result = model.predict([[hours]])

print(result)
if result == 1:
    print(f"Based on your srtudied hours {hours}, you are likely to pass the exam ")
else:
    print(f"Based on your studied hours {hours}, you are likely to fail the exam ")

[1]
Based on your srtudied hours 5.0, you are likely to pass the exam 


## Multiple Logistic Regression 

In [3]:
# Multinomial Logistic Regression (3-class classification)
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load full Iris dataset (3 classes: 0,1,2)
iris = load_iris()
X = iris.data
y = iris.target

# Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Create multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)

# Train model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9333333333333333

Confusion Matrix:
 [[15  0  0]
 [ 0 14  1]
 [ 0  2 13]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



c:\Users\Abdul Rehman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
